spring:
  datasource:
    url: jdbc:mysql://mysql80.server.com:10080/core_db?characterEncoding=UTF-8
    username: root
    password: 123456
    hikari:
      # 最小空闲连接数量
      minimum-idle: 5
      # 空闲连接最大存活时间
      idle-timeout: 60000
      # 最大连接池数量
      maximum-pool-size: 15
      # 连接超时时间
      connection-timeout: 30000

mybatis:
  # xml 文件位置
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    # 开启驼峰转换
    map-underscore-to-camel-case: true