management:
  health:
    mail:
      # 邮件健康检查
      enabled: false
spring:
  mail:
    # smtp服务主机
    host: smtp.163.com
    # 163 邮箱示例地址
    username: xxx@163.com
    # 163 邮箱示例密码
    password: xxx
    # SMTP 服务端口
    port: 465
    # 服务协议
    protocol: smtps
    # 默认编码
    default-encoding: UTF-8
    # 服务器连通性测试
    test-connection: false