server:
  port: 8080
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: core-server
  profiles:
    active:
      - redis
      - datasource
      - email
      - zy

logging:
  level:
    - com.zy.server.core: debug